# The ?= means: only assign the value to the variable if the variable
# isn't already set to some value.
#
# So, to use another compiler / flags run make in this way:
# CXX=g++-3.4 CXXFLAGS="" make

LD = g++
CXX = g++
CXXFLAGS = -Wall -pedantic -ansi -std=c++0x -g